version: "3"

services:
  db:
    image: postgres
    container_name: coffee_db
    volumes:
      - coffee_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6000:5432"
  web:
    build: .
    container_name: coffee-backend-web
    command: bash -c "npm run dev"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always
volumes:
  coffee_database:
    external: true
